name: 'Ruby Review Action'
description: 'Container Action to check files in a repo'
author: '@shmeadyy'
inputs: 
  token:
    description: 'OAuth Token to Use for GH'
    default: null
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - inputs.token
