name: 'Ruby Review Action'
description: 'Hello World with Container Action'
author: '@shmeadyy'
inputs: 
  myInput:
    description: 'Input to use'
    default: 'world'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ secrets.GITHUB_TOKEN }}
